/*
  # Create contacts table

  1. New Tables
    - `contacts`
      - `id` (bigint, primary key)
      - `first_name` (text, not null)
      - `last_name` (text)
      - `phone` (text)
      - `age1` (integer)
      - `image_url` (text)
      - `approved` (boolean, default: false)
      - `created_at` (timestamptz, default: now())

  2. Security
    - Enable RLS on contacts table
    - Add policies for all operations
*/

-- Drop existing table if it exists
DROP TABLE IF EXISTS contacts;

-- Create the contacts table with all required columns
CREATE TABLE IF NOT EXISTS contacts (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name text NOT NULL,
    last_name text,
    phone text,
    age1 integer,
    image_url text,
    approved boolean DEFAULT FALSE,
    created_at timestamptz DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Enable read access for all users" ON contacts
    FOR SELECT
    TO public
    USING (true);

CREATE POLICY "Enable insert access for all users" ON contacts
    FOR INSERT
    TO public
    WITH CHECK (true);

CREATE POLICY "Enable update access for all users" ON contacts
    FOR UPDATE
    TO public
    USING (true);

CREATE POLICY "Enable delete access for all users" ON contacts
    FOR DELETE
    TO public
    USING (true);
